[project]
name = "source-code-export"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyinstaller>=6.12.0",
    "ruff>=0.11.2",
]
